export const menuItems = [{
        id: 1,
        label: "menuitems.menu.text",
        isTitle: true,
        user: [],
    },
    {
        id: 2,
        label: "menuitems.dashboards.text",
        icon: "bx-home-circle",
        link: "/home",
        user: [],
    },
    {
        id: 3,
        label: "menuitems.users.text",
        icon: "bxs-user-circle",
        link: "/users",
        user: ['Super Administrator'],
    },
    {
        id: 4,
        label: "menuitems.locations.text",
        icon: "bx-map",
        link: "/locations",
        user: ['Super Administrator'],
    },
    {
        id: 5,
        label: "menuitems.agencies.text",
        icon: "bxs-city",
        link: "/agencies",
        user: ['Super Administrator'],
    },
    {
        id: 6,
        label: "menuitems.programs.text",
        icon: "bx-category-alt",
        link: "/programs",
        user: ['Super Administrator'],
    },
    {
        id: 10,
        label: "menuitems.schools.text",
        icon: "bxs-school",
        link: "/schools",
        user: ['Super Administrator'],
    },
    {
        id: 7,
        label: "menuitems.courses.text",
        icon: "bxs-graduation",
        link: "/courses",
        user: ['Super Administrator'],
    },
    {
        id: 8,
        label: "menuitems.expenses.text",
        icon: "bx-credit-card-alt",
        link: "/expenses",
        user: ['Super Administrator'],
    },
    {
        id: 9,
        label: "menuitems.logs.text",
        icon: "bx-message-square-dots",
        link: "/logs",
        user: ['Super Administrator'],
    },

];